### ISSUE TITLE
[Feature] ddl은 docker에서 초기화 하는 용도로만 사용하기

### ISSUE THREAD

**Issue by f-lab-lion** [f-lab-edu/unique-auction#51]
**목표**
ddl을 spring에서 초기화 하는 용도로 사용하지 않고
docker로 mysql이 올라갈때 실행하는 방식으로 변경하기.

as-is : docker에서 실행된 mysql은 테이블이 하나도 없는 비어있는 상태이고, application 이 실행되면서 초기화 한다.
to-be : docker에서 mysql을 올릴때 ddl을 사용해 초기화한다. application이 실행될때는 `이미 만들어져 있는 DB에 붙어서` 실행되는 구조.

**방법**
설정 `spring.sql.init.mode` 제거.
```yml
spring:
  sql:
    init:
      mode: always
```
